displayName=Black Chinchompa Highlighter
author=Tenai
description=Highlights the four Black Chinchompas you typically need to shoot
tags=chinchompa,highlight,chin,black
plugins=me.tenai.blackchinhighlighter.BlackChinHighlighterPlugin